name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Use Node.js 14.x

    - name: Install Dependencies and Build
      run: |
        cd frontend
        npm install
        npm run build

    - name: List all directories
      run: |
        find . -type d

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get install openssh-client -y
      
    - name: List directory contents
      run: |
        ls -l frontend/
        ls -l frontend/dist/

    - name: Copy files
      run: cp -r dist/* /var/www/html/facetea2
      working-directory: frontend
        

