name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  build_deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Use Node.js 14.x

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # Cache key typically includes the workflow file, runner type, and a hash of the dependency files (e.g., package-lock.json)
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
        path: frontend/node_modules

    - name: Install Dependencies and Build
      run: |
        cd frontend
        npm ci --legacy-peer-deps
        npm run build

    - name: List directory contents
      run: |
        ls -l frontend/
        ls -l frontend/dist/
        
    - name: Copy files
      run: |
        cd frontend
        cp -r dist/* /var/www/html/facetea2
