name: Build and Deploy


on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Use Node.js 14.x

    - name: Install Dependencies and Build
      run: |
        cd frontend
        npm install
        npm run build

    - name: List all directories
      run: |
        find . -type d

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: List directory contents
      run: |
        ls -l frontend/
        ls frontend
       

    - name: Copy files
      run: |
        
        cp -r dist/* /var/www/html/facetea2
      
        

